name: conda R packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -f conda.Dockerfile -t my-conda-name .
    - run: docker run --rm --name my_pipeline_container -v /github/workspace/output/:/workspace/output/:rw my-conda-name
    - uses: actions/upload-artifact@v3
      with:
        path: /github/workspace/output/
