name: Last version R packages using r2u

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -f r2u.Dockerfile -t my-r2u-name .
    - run: docker run --rm --name my_pipeline_container -v /github/workspace/output/:/workspace/output/:rw my-r2u-name
    - uses: actions/upload-artifact@v4
      with:
        path: /github/workspace/output/
