name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -f renv.Dockerfile -t my-renv-name .
    - run: docker run --rm --name my_renv_container -v /github/workspace/output/:/workspace/output/:rw my-renv-name
    - uses: actions/upload-artifact@v3
      with:
        path: /github/workspace/output/
